services:
  postgres:
    image: postgres:16
    container_name: ecg_postgres
    environment:
      POSTGRES_DB: ecg_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ecg_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecg_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    image: thanglele/ecgapi:latest
    container_name: ecg_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=ecg_db;Username=postgres;Password=123456
      Jwt__Key: THIS_IS_DEV_ONLY_CHANGE_ME_TO_A_LONG_RANDOM_SECRET_1234567890
      Jwt__Issuer: ECG.Api
      Jwt__Audience: ECG.Clients
      Jwt__ExpMinutes: "240"
    ports:
      - "8087:8080"
    volumes:
      - ecg_uploads:/app/uploads

volumes:
  ecg_pgdata:
  ecg_uploads:
